<div>
<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHyzbVaQYmLCC_zoINZ4dhhSX2upH6QThkMUWVlEAqYQzARYbh1zuqhuY&s=10" width="150"/>
    <br>
    <strong>Universidad De Los Lagos</strong><br>
    <em>Ingeniería Civil en Informática</em><br>
    <em>Profesor: Victor Saldivia Vera</em><br>
    <em>Asignatura: Programación</em><br>

</div>

### **TRABAJANDO CON ARREGLOS**

#### **Importando librería numpy**

In [1]:
import numpy as np

##### Creando una lista de 10 Elementos

In [2]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

##### Transformando la Lista a un Array

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Corroborando el tipo de estructura


In [4]:
type(arreglo)

numpy.ndarray

##### Corroborando el tipo de datos del arreglo


In [5]:
arreglo.dtype

dtype('int64')

##### Definiendo el Array de int64 a float32


In [6]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### Sigue siendo un array de int32


In [8]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Transformando los datos de int64 a float32


In [9]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

##### También existe una función similar a Range pero ocupando Arrays

In [10]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##### Arreglo de 2 en 2 utilizando Arange

In [12]:
arreglonuevo2 = np.arange(1,11,3)
arreglonuevo2

array([ 1,  4,  7, 10])

<h4 style = "color:lightblue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h4>
<h4 style = "color:aquamarine">Obteniendo el promedio del array</h3>


In [13]:
promedio = np.mean(arreglo)
promedio

np.float64(5.5)

<h4 style = "color:aquamarine">Obteniendo la mediana del array</h4>


In [14]:
mediana = np.median(arreglo)
mediana

np.float64(5.5)

<h4 style = "color:aquamarine"> Desviación Estandar del Arreglo </h4>


In [15]:
desviacion_std = np.std(arreglo)
desviacion_std

np.float64(2.8722813232690143)

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo unos </h4>

In [16]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h4 style = "color:aquamarine"> Generación de un arreglo de 10 elementos de solo ceros </h4>

In [17]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h4 style = "color:aquamarine"> Transformando el arreglo de unos de punto flotante a enteros </h4>


In [18]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3 style = "color:orange"> <b>UTILIZANDO LA FUNCIÓN RANDOM</b> </h4>
<h4 style = "color:yellow"> Generando arreglo aleatorio de 5 elementos de Número entre 0 y 1</h4>



In [41]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio 

array([0.62968612, 0.58483003, 0.27823616, 0.44403623, 0.32948738])

<h4 style = "color:yellow"> Generando una matriz aleatoria de 3x3</h4>


In [61]:
matriz = np.random.rand(5,5)
matriz

array([[0.88103399, 0.34717037, 0.6944111 , 0.02747142, 0.03519351],
       [0.05415352, 0.73997092, 0.00876736, 0.32014393, 0.84767828],
       [0.37154698, 0.25707061, 0.87895562, 0.00686355, 0.49544754],
       [0.78986037, 0.02769328, 0.70095636, 0.53171434, 0.12263444],
       [0.27548698, 0.93507943, 0.67246923, 0.12188898, 0.94195454]])

<h4 style = "color:yellow"> Generando un arreglo aleatorio de 10 números enteros del 1 al 5</h4>


In [93]:
arreglo_aleatorio2  = np.random.randint(1,101,10)
arreglo_aleatorio2

array([32, 79, 97, 42, 60, 40, 76, 17, 42, 45], dtype=int32)

<h4 style = "color:yellow"> Generando una matriz aleatoria de 10 números enteros del 1 al 100</h4>


In [117]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[ 28,  17,  43,  82,  65,  73,  16,  16,  15,  21],
       [ 39,  88,  39,  71,  29,  13,  65,  49,  21,  74],
       [ 44,  67,  70,  59,  57,  44,  60,  86,  32,  17],
       [ 45,  46,  27,  16,  77,  98,  20,  47,  53,  96],
       [ 47,   5,  91,  34,  27,  50,  90,  42,  69,  58],
       [ 15,  14,  39,  47,   9,  20,  58,  72, 100,  83],
       [ 88,  28,  49,  28,  50,   9,   8,  54,  41,  65],
       [ 58,  57,  62,  72,  35,  18,  97,  26,  79,   3],
       [ 73,  12,  75,  76,  40,  91,   8,  90,  85,  84],
       [ 65,  72,  12,  21,  52,  14,  50,  44,   9,  98]], dtype=int32)